### ISSUE TITLE
circleciでテストしたとき、時刻のテストがtimezone違いでNGになる。

### ISSUE THREAD

**Issue by ktr11** [ktr11/booster#47]
#45 実施中に発生。
https://app.circleci.com/pipelines/github/ktr11/booster/35/workflows/db919644-53b4-4be6-9912-f47958e8e5a3/jobs/63/parallel-runs/0/steps/0-107

## テストコード(該当部分抜粋)
```rb
    it '予定を登録できる' do
      plan_count = Plan.count
      user = create(:user)
      login_as(user)
      post '/plans', params: {
        plan: plan_params
      }
      plan = Plan.find_by(title: 'test1')
      expect(response).to have_http_status(302)
      is_expected.to redirect_to("/plans/#{plan.id}")
      get "/plans/#{plan.id}"
      expect(response.body).to include('予定を登録しました。')
      expect(plan_count + 1).to eq Plan.count
      plan = Plan.find_by(title: 'test1')
      expect(plan).to_not eq nil
      expect(plan.user).to eq user
      expect(plan.title).to eq 'test1'
      expect(plan.content).to eq 'hogehoge'
      expect(plan.start_date).to eq Date.new(2020, 1, 1)
      expect(plan.start_time).to eq Time.new(2000, 1, 1, 9, 0, 0)
      expect(plan.end_date).to eq Date.new(2020, 1, 1)
      expect(plan.end_time).to eq Time.new(2000, 1, 1, 18, 0, 0)
      expect(plan.all_day).to eq false
      expect(plan.done).to eq false
    end
```

## circleciでのテスト結果
```sh
#!/bin/bash -eo pipefail
bundle exec rspec
Running via Spring preloader in process 292
..........................F............F....................

Failures:

  1) Plans POST /plans 予定を登録できる
     Failure/Error: expect(plan.start_time).to eq Time.new(2000, 1, 1, 9, 0, 0)
     
       expected: 2000-01-01 09:00:00.000000000 +0000
            got: 2000-01-01 09:00:00.000000000 +0900
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -2000-01-01 09:00:00 +0000
       +Sat, 01 Jan 2000 09:00:00.000000000 JST +09:00
       
     # ./spec/requests/plans_spec.rb:51:in `block (3 levels) in <main>'

  2) Plans POST /plans PATCH /plans/plan.id 予定を更新できる
     Failure/Error: expect(plan.start_time).to eq Time.new(2000, 1, 1, 20, 0, 0)
     
       expected: 2000-01-01 20:00:00.000000000 +0000
            got: 2000-01-01 20:00:00.000000000 +0900
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -2000-01-01 20:00:00 +0000
       +Sat, 01 Jan 2000 20:00:00.000000000 JST +09:00
       
     # ./spec/requests/plans_spec.rb:233:in `block (4 levels) in <main>'

Finished in 1.26 seconds (files took 2.11 seconds to load)
60 examples, 2 failures

Failed examples:

rspec ./spec/requests/plans_spec.rb:32 # Plans POST /plans 予定を登録できる
rspec ./spec/requests/plans_spec.rb:213 # Plans POST /plans PATCH /plans/plan.id 予定を更新できる


Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by ktr11** [comment]
```yml
    docker:
      - image: cimg/ruby:3.0.2-node
        environment:
          - RAILS_ENV: test
          - BUNDLE_PATH: vendor/bundle
          - MYSQL_HOST: db
          - MYSQL_PASSWORD: password
          - MYSQL_PORT: 3306
          - TZ: "Asia/Tokyo" # これ！
```
としたら解決した。
1d4be96
