### ISSUE TITLE
`rails s`でwebpackerのエラー

### ISSUE THREAD

**Issue by ktr11** [ktr11/booster#8]
`rails s`実行で以下のエラーとなり起動しない
```bash
$ bundle exec rails s
=> Booting Puma
=> Rails 6.1.4 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
/Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:103:in `rescue in load': Webpacker configuration file not found /Users/ktr11/portfolio/booster/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /Users/ktr11/portfolio/booster/config/webpacker.yml (RuntimeError)
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:95:in `load'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:92:in `data'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:88:in `fetch'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:43:in `public_path'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:47:in `public_output_path'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:51:in `public_manifest_path'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/manifest.rb:83:in `load'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/manifest.rb:18:in `refresh'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/commands.rb:47:in `bootstrap'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker.rb:35:in `bootstrap'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/railtie.rb:41:in `block in <class:Engine>'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/initializable.rb:32:in `run'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/application.rb:391:in `initialize!'
	from /Users/ktr11/portfolio/booster/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:37:in `start'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:135:in `perform'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/command/base.rb:69:in `perform'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/command.rb:48:in `invoke'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/ktr11/portfolio/booster/bin/rails:5:in `<top (required)>'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/client/rails.rb:30:in `load'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/client/rails.rb:30:in `call'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/client/command.rb:7:in `call'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/client.rb:30:in `run'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/bin/spring:49:in `<top (required)>'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `load'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/ktr11/portfolio/booster/bin/spring:10:in `require'
	from /Users/ktr11/portfolio/booster/bin/spring:10:in `block in <top (required)>'
	from <internal:kernel>:90:in `tap'
	from /Users/ktr11/portfolio/booster/bin/spring:7:in `<top (required)>'
	from bin/rails:2:in `load'
	from bin/rails:2:in `<main>'
/Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/psych.rb:581:in `initialize': No such file or directory @ rb_sysopen - /Users/ktr11/portfolio/booster/config/webpacker.yml (Errno::ENOENT)
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/psych.rb:581:in `open'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/psych.rb:581:in `load_file'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/compile_cache/yaml.rb:307:in `load_file'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:97:in `load'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:92:in `data'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:88:in `fetch'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:43:in `public_path'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:47:in `public_output_path'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/configuration.rb:51:in `public_manifest_path'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/manifest.rb:83:in `load'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/manifest.rb:18:in `refresh'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/commands.rb:47:in `bootstrap'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker.rb:35:in `bootstrap'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/webpacker-5.4.3/lib/webpacker/railtie.rb:41:in `block in <class:Engine>'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/initializable.rb:32:in `run'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /Users/ktr11/.rbenv/versions/3.0.2/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/application.rb:391:in `initialize!'
	from /Users/ktr11/portfolio/booster/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:37:in `start'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands/server/server_command.rb:135:in `perform'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/command/base.rb:69:in `perform'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/command.rb:48:in `invoke'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/railties-6.1.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/ktr11/portfolio/booster/bin/rails:5:in `<top (required)>'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/client/rails.rb:30:in `load'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/client/rails.rb:30:in `call'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/client/command.rb:7:in `call'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/client.rb:30:in `run'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/bin/spring:49:in `<top (required)>'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `load'
	from /Users/ktr11/portfolio/booster/vendor/bundle/ruby/3.0.0/gems/spring-4.0.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/ktr11/portfolio/booster/bin/spring:10:in `require'
	from /Users/ktr11/portfolio/booster/bin/spring:10:in `block in <top (required)>'
	from <internal:kernel>:90:in `tap'
	from /Users/ktr11/portfolio/booster/bin/spring:7:in `<top (required)>'
	from bin/rails:2:in `load'
	from bin/rails:2:in `<main>'
```

**Comment by ktr11** [comment]
## webpackerのinstallでyarnが入っていないと怒られる。
```bash
ktr11@ktrmac:~/portfolio/booster (issue8-rails-s-error)
$ bundle exec rails webpacker:install
Warning: you are using an unstable release of Node.js (v17.1.0). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/
Exiting!
```

## yarnを入れてみる
```bash
ktr11@ktrmac:~/portfolio/booster (issue8-rails-s-error)
$ brew install yarn
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

You have 17 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Downloading https://ghcr.io/v2/homebrew/core/yarn/manifests/1.22.19
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/yarn/blobs/sha256:79b90324a5365189a144b786e9bdb3bf32be3823e9041d5f3250ea7b804dcd0b
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:79b90324a5365189a144b786e9bdb3bf32be3823e9041d5f3250ea7b804dcd0b?se=2022-06-17T08%3A45%3A00Z&sig=C3Xj2oNGi7fSnhFN4mQN
######################################################################## 100.0%
==> Pouring yarn--1.22.19.all.bottle.tar.gz
==> Caveats
yarn requires a Node installation to function. You can install one with:
  brew install node
==> Summary
🍺  /usr/local/Cellar/yarn/1.22.19: 15 files, 5MB
==> Running `brew cleanup yarn`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```
→このあと `bundle exec rails webpacker:install` したらうまくいった。

**Comment by ktr11** [comment]
マージ済みなのでクローズ
